services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone
    container_name: xbackbone
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${VOLUME_STORAGE:-/mnt/docker-volumes}/xbackbone:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
