version: "3.8"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    environment:
      - GOTIFY_DEFAULTUSER_NAME
      - GOTIFY_DEFAULTUSER_PASS
    volumes:
      - ${VOLUME_STORAGE:-/mnt/docker-volumes}/gotify:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gotify.loadbalancer.passhostheader=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "traefik.http.services.gotify.loadbalancer.sticky=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
