api:
  dashboard: true # optional

log:
  level: INFO

accessLog:
  filePath: "/logs/traefik.log"
  format: json
  filters:
    statusCodes:
      - "400-599"
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - security-headers@file
        - rate-limit@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: YOUR_DOMAIN # Change to your domain
            sans:
              - "*.YOUR_DOMAIN" # Same as above

providers:
  docker:
    watch: true
    network: proxy # Docker network name here
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.YOUR_DOMAIN`)" # Change to your proxy domain
    exposedByDefault: false
  file:
    filename: dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: YOUR_EMAIL # Needs to be a valid email address
      storage: acme.json
      keyType: EC384
      dnsChallenge:
        provider: cloudflare # If you use cloudflare, if not then change
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
