version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_NOTIFICATIONS
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro